name: CI

on: [push]

jobs:
  macos:
    runs-on: macOS-latest

    strategy:
      matrix:
        xcode: ["11.4", "11.3"]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install System Dependencies
        if: matrix.xcode == '11.3'
        run: brew bundle
      - name: Build and Test
        run: swift test
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        swift: ["5.2", "5.1"]

    container:
      image: swift:${{ matrix.swift }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install System Dependencies
        run: |
          apt-get update
          apt-get install -y libxml2-dev
      - name: Build and Test
        run: swift test --enable-test-discovery
